In [2]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns",None)

In [2]:
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
pd.set_option("display.max_columns",None)
pd.set_option("display.max_colwidth",None)
import os
from datetime import datetime
import unicodedata
from pathlib import Path
from rapidfuzz import fuzz
home = Path.home()

# Esto es un proceso de limpieza provisional

In [60]:
#Estas placas salieron de detección 2021-2024, se los pasamos a fisca para verificar pq no tienen partidas
#Algunas quedaron con novedades y persona indeterminada
revision_fisca = pd.read_excel(r"C:\Users\Katherine Builes L\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\revisa_fisca_valoracion_final.xlsx",sheet_name=None)

In [62]:
revision_fisca.keys()

dict_keys(['Hoja1', 'base_de_datos', 'LAURA_REVISAR_NO NOTIFICADO_DOM'])

In [63]:
base_de_datos = revision_fisca["base_de_datos"]

In [64]:
base_de_datos.sample(2)

,Unnamed: 0,PLACA,VIGENCIA,CLAVE,PERTENENCIA_DOMINA,PARTIDA_ABIERTA,CON_PAGO,ESTADO,OBSERVACION,FECHA
4703,5532,NBA811,2022,NBA811-2022,NOTIFICADO_PARA_DOMINA,NO TIENE PARTIDA,NO TIENE PAGO,LIQUIDA BIEN,NaN,NaN
7588,9149,KEB344,2023,KEB344-2023,NO_NOTIFICADO_PARA_DOMINA,NO TIENE PARTIDA,NO TIENE PAGO,LIQUIDA BIEN,NaN,NaN

In [65]:
base_de_datos["ESTADO"].value_counts()

ESTADO
LIQUIDA BIEN      30517
NOVEDAD OK         1520
PAGADA              108
Valor factura         2
Name: count, dtype: int64

In [71]:
base_de_datos = base_de_datos[base_de_datos["ESTADO"]!="LIQUIDA BIEN"]

In [72]:
diccionario_base_de_datos = base_de_datos.set_index(["CLAVE"])["ESTADO"]

In [73]:
diccionario_base_de_datos

CLAVE
VZJ60-2021     NOVEDAD OK
VZI02-2021     NOVEDAD OK
VZF15-2021     NOVEDAD OK
VZC65-2021     NOVEDAD OK
UPI012-2021    NOVEDAD OK
                  ...
ADB612-2024    NOVEDAD OK
ACI855-2024    NOVEDAD OK
ACC925-2024    NOVEDAD OK
ABE976-2024    NOVEDAD OK
ABB647-2024    NOVEDAD OK
Name: ESTADO, Length: 1630, dtype: object

In [3]:
cartera = pd.read_parquet(r"C:\Users\Katherine Builes L\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\output\20260309_parque_omiso_clasificacion_persona_clase.parquet")

In [3]:
ruta = home / "OneDrive - Valor+ SAS/analitica_impuestos/depurada/partidas.parquet"

partidas = pd.read_parquet(ruta)

In [6]:
partidas[partidas["PLACA"]=="JCS123"]

,PLACA,FECHA_PARTIDA,INTERLOCUTOR,CUENTA_CONTRATO,REFERENCIA,VIGENCIA,ID_USUARIO,NOMBRES,APELLIDOS,RAZON_SOCIAL,PROCEDRECL,NIV_RECLAMACION,AVALUO,IMPUESTO,SANCIONES,INTERESES,SISTEMATIZACION,TOTAL
1015214,JCS123,2026-03-13,1000428086,020000799006,0000000306315035,2017,98510776,WILMAR DE JESUS,URAN VASCO,None,13,13,82451613.00,2061000.00,4122000.00,3397000.00,21450.00,9601450.00
1661474,JCS123,2026-03-13,1000428086,020000799006,0000000309266578,2020,98510776,WILMAR DE JESUS,URAN VASCO,None,13,12,61260000.00,1532000.00,3064000.00,1400000.00,21450.00,6017450.00
1916240,JCS123,2026-03-13,1000428086,020000799006,0000003400320016,2021,98510776,WILMAR DE JESUS,URAN VASCO,None,13,11,59420000.00,1486000.00,2972000.00,1898000.00,21450.00,6377450.00
2186532,JCS123,2026-03-13,1000428086,020000799006,0000003100378338,2022,98510776,WILMAR DE JESUS,URAN VASCO,None,13,11,60280000.00,1507000.00,3014000.00,675000.00,21450.00,5217450.00
2496184,JCS123,2026-03-13,1000428086,020000799006,0000000313099742,2023,98510776,WILMAR DE JESUS,URAN VASCO,None,13,11,53050000.00,1326000.00,212000.00,67000.00,21450.00,1626450.00
2835701,JCS123,2026-03-13,1000428086,020000799006,0000003000932511,2024,98510776,WILMAR DE JESUS,URAN VASCO,None,13,03,45090000.00,676000.00,0.00,0.00,23400.00,699400.00

In [4]:
cartera[cartera["PLACA"]=="040AEN"]

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,FECHA_MATRICULA,IMPUESTO,SANCIONES,INTERESES,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS,PLACA-VIGENCIA,ID_NORMALIZADO_v1,ID_NORMALIZADO,TIPO_PERSONA,NOMBRE_COMPLETO,CLASE_TIPIFICADA
3828884,040AEN,PLACA OMISA,CAÑASGORDAS,ANTIOQUIA,None,21610744,C,2025,OCCIDENTE,MOTOCICLETAS,2022-02-16,NaN,NaN,NaN,NaN,NaN,NaN,040AEN-2025,21610744,21610744,PERSONA NATURAL,ANA ROSA HERCILIA ESCOBAR,MOTOCICLETAS
5173186,040AEN,PLACA OMISA,CAÑASGORDAS,ANTIOQUIA,None,21610744,C,2026,OCCIDENTE,MOTOCICLETAS,2022-02-16,NaN,NaN,NaN,NaN,NaN,NaN,040AEN-2026,21610744,21610744,PERSONA NATURAL,ANA ROSA HERCILIA ESCOBAR,MOTOCICLETAS

In [68]:
cartera.sample(1)

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,FECHA_MATRICULA,IMPUESTO,SANCIONES,INTERESES,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS,PLACA-VIGENCIA,ID_NORMALIZADO_v1,ID_NORMALIZADO,TIPO_PERSONA,NOMBRE_COMPLETO,CLASE_TIPIFICADA
5087842,CFL15E,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,1128277610,C,2026,VALLE DEL ABURRA,MOTOCICLETAS,2016-04-22,41000.0,0.0,0.0,41000.0,262000.0,0.0,CFL15E-2026,1128277610,1128277610,PERSONA NATURAL,DANIEL CARDONA SANCHEZ,MOTOCICLETAS

In [67]:
cartera["ESTADO"].value_counts()

ESTADO
PLACA OMISA              5203402
PERSONA INDETERMINADA     511429
PÉRDIDA DE POSESIÓN           29
Name: count, dtype: int64

In [ ]:
cartera = cartera[cartera["PLACA-VIGENCIA"].replace(diccionario_base_de_datos)]

KeyError: "None of [Index(['ZXZ97-2009', 'ZXZ80-2009', 'ZXZ70-2009', 'ZXZ50-2009', 'ZXZ40-2009',\n       'ZXZ23-2009', 'ZXY99-2009', 'ZXY98-2009', 'ZXY79-2009', 'ZXY77-2009',\n       ...\n       '017AAC-2026', '009ACW-2026', '009ACP-2026', '009AAC-2026',\n       '005AAC-2026', '002ABZ-2026', '002AAM-2026', '001AAA-2026',\n       '000AEE-2026', '000AAA-2026'],\n      dtype='object', length=5714860)] are in the [columns]"

In [ ]:
cartera["ESTADO"].value_counts()

In [29]:
indeterminados = cartera[cartera["ESTADO"]=="PERSONA INDETERMINADA"]

In [51]:
indeterminados = indeterminados[["PLACA","VIGENCIA","ESTADO"]]

In [52]:
indeterminados

          PLACA  VIGENCIA                 ESTADO
158406   RAG565      2010  PERSONA INDETERMINADA
158407   PKU47A      2010  PERSONA INDETERMINADA
158408   OME789      2010  PERSONA INDETERMINADA
158409   OM5805      2010  PERSONA INDETERMINADA
158410   NVL776      2010  PERSONA INDETERMINADA
...         ...       ...                    ...
4048701  002ABZ      2025  PERSONA INDETERMINADA
4048702  002AAM      2025  PERSONA INDETERMINADA
4048703  001AAA      2025  PERSONA INDETERMINADA
4048704  000AEE      2025  PERSONA INDETERMINADA
4048705  000AAA      2025  PERSONA INDETERMINADA

[438889 rows x 3 columns]

In [54]:
indeterminados.to_excel("indeterminados.xlsx",index=False)

In [32]:
indeterminados.shape

(438889, 24)

In [31]:
indeterminados["PLACA"].nunique()

65242

In [28]:
pd.crosstab(cartera["ESTADO"],cartera["VIGENCIA"])

VIGENCIA,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
ESTADO,,,,,,,,,,,,,,,,
PERSONA INDETERMINADA,1265,2449,4736,5497,7728,12116,17997,22213,26401,30948,35745,41785,48571,56379,60858,64201
PLACA OMISA,94550,104185,116966,129097,141588,153230,167555,183044,200812,213549,245964,262260,295120,333996,386677,495447
PÉRDIDA DE POSESIÓN,2,2,2,1,1,2,2,0,0,0,0,4,5,6,0,0

In [33]:
revisa_fiscaliza = cartera[cartera["FUENTE"]=="DETECCION"]

In [34]:
revisa_fiscaliza.shape

(758020, 24)

In [36]:
revisa_fiscaliza = revisa_fiscaliza[revisa_fiscaliza["VIGENCIA"]>2020]

In [37]:
revisa_fiscaliza.shape

(654100, 24)

In [38]:
revisa_fiscaliza = revisa_fiscaliza[revisa_fiscaliza["ESTADO"]=="PLACA OMISA"]

In [39]:
revisa_fiscaliza.shape

(421807, 24)

In [40]:
revisa_fiscaliza["VIGENCIA"].value_counts()

VIGENCIA
2025    386553
2024     24981
2021      3725
2022      3502
2023      3046
Name: count, dtype: int64

In [50]:
revisa_fiscaliza.to_parquet("revisa_fiscaliza.parquet",index=False)

# CARTERA

In [2]:
import pandas as pd
import numpy as np

In [3]:
cartera = pd.read_parquet(r"C:\Users\Katherine Builes L\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\output\20260409_parque_omiso_clasificacion_persona_clase.parquet")

In [4]:
cartera = cartera[cartera["VIGENCIA"]!=2009]

In [5]:
cartera = cartera[cartera["VIGENCIA"]!=2026]

In [6]:
cartera.shape

(3951567, 23)

In [7]:
cartera.head()

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,...,INTERESES,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS,PLACA-VIGENCIA,ID_NORMALIZADO_v1,ID_NORMALIZADO,TIPO_PERSONA,NOMBRE_COMPLETO,CLASE_TIPIFICADA
0,ZXZ97,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,98559636,CC,2010,VALLE DEL ABURRA,MOTOCICLETAS,...,84000.0,52000.0,262000.0,218000.0,ZXZ97-2010,98559636,98559636,PERSONA NATURAL,DUVIAN DARIO BURITICA RAMIREZ,MOTOCICLETAS
1,ZXZ80,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,98526642,1,2010,VALLE DEL ABURRA,MOTOCICLETAS,...,10000.0,11000.0,262000.0,46000.0,ZXZ80-2010,98526642,98526642,PERSONA NATURAL,OSCAR ALONSO AGUDELO MEJIA,MOTOCICLETAS
2,ZXZ70,PLACA OMISA,YOLOMBO,ANTIOQUIA,None,71172083,1,2010,NORDESTE,MOTOCICLETAS,...,0.0,22000.0,262000.0,93000.0,ZXZ70-2010,71172083,71172083,PERSONA NATURAL,NELSON ALBEIRO ORREGO PUERTA,MOTOCICLETAS
3,ZXZ50,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,8000682800,N,2010,VALLE DEL ABURRA,MOTOCICLETAS,...,0.0,11000.0,262000.0,46000.0,ZXZ50-2010,8000682800,8000682800,PERSONA JURIDICA,CODEMARCAS LTDA.,MOTOCICLETAS
4,ZXZ40,PLACA OMISA,LA CEJA,ANTIOQUIA,None,71629485,C,2010,ORIENTE,MOTOCICLETAS,...,0.0,11000.0,262000.0,46000.0,ZXZ40-2010,71629485,71629485,PERSONA NATURAL,OSCAR ALVARO ECHAVARRIA ORDOÑEZ,MOTOCICLETAS

In [8]:
cartera["FUENTE"] = np.where(
    cartera["IMPUESTO"].isnull(),"DETECCION","PARTIDAS"
)

In [9]:
cartera["FUENTE"].value_counts()

FUENTE
PARTIDAS     3196976
DETECCION     754591
Name: count, dtype: int64

In [10]:
cartera["FUENTE"].value_counts(normalize=True)

FUENTE
PARTIDAS     0.80904
DETECCION    0.19096
Name: proportion, dtype: float64

In [11]:
cartera[cartera["PLACA"]=="421AEM"]

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,...,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS,PLACA-VIGENCIA,ID_NORMALIZADO_v1,ID_NORMALIZADO,TIPO_PERSONA,NOMBRE_COMPLETO,CLASE_TIPIFICADA,FUENTE
2413393,421AEM,PLACA OMISA,ITAGUI,ANTIOQUIA,None,43441480,C,2022,VALLE DEL ABURRA,MOTOCICLETAS,...,151000.0,303000.0,174000.0,421AEM-2022,43441480,43441480,PERSONA NATURAL,LILIANA MARCELA RAMIREZ GIRALDO,MOTOCICLETAS,PARTIDAS
3731088,421AEM,PLACA OMISA,ITAGUI,ANTIOQUIA,None,43441480,C,2025,VALLE DEL ABURRA,MOTOCICLETAS,...,130000.0,262000.0,22000.0,421AEM-2025,43441480,43441480,PERSONA NATURAL,LILIANA MARCELA RAMIREZ GIRALDO,MOTOCICLETAS,PARTIDAS

In [12]:
pd.crosstab(cartera["FUENTE"], cartera["VIGENCIA"])

VIGENCIA,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
FUENTE,,,,,,,,,,,,,,,,
DETECCION,5503,5200,2563,1658,2430,4186,12914,4277,17378,22370,28511,36170,37565,48295,84196,441375
PARTIDAS,90194,101301,119028,132832,146797,161076,172519,200844,209638,221967,252891,267484,305419,341009,361503,112474

In [13]:
pd.crosstab(cartera["FUENTE"], [cartera["ESTADO"], cartera["VIGENCIA"]],margins=True)

ESTADO    PERSONA INDETERMINADA                                               \
VIGENCIA                   2010  2011  2012  2013  2014   2015   2016   2017
FUENTE
DETECCION                   102   144   156   168  1064   1887  11375   3778
PARTIDAS                   1163  2305  4580  5329  6664  10227   6621  18434
All                        1265  2449  4736  5497  7728  12114  17996  22212

ESTADO                   ... PÉRDIDA DE POSESIÓN                           \
VIGENCIA    2018   2019  ...                2011 2012 2013 2014 2015 2016
FUENTE                   ...
DETECCION  16335  20688  ...                   1    1    1    1    1    1
PARTIDAS   10065  10257  ...                   1    1    0    0    1    1
All        26400  30945  ...                   2    2    1    1    2    2

ESTADO                        All
VIGENCIA  2021 2022 2023
FUENTE
DETECCION    1    2    1   754591
PARTIDAS     3    3    5  3196976
All          4    5    6  3951567

[3 rows x 43 columns]

In [15]:
5342+	4977+	2280	+1345	+1224	+2161+	1380	+309+	806	+329	+452	+3725+	3502	+3046	+24981+	386553

442412

In [16]:
pd.crosstab(cartera["FUENTE"], [cartera["VIGENCIA"], cartera["ESTADO"]],margins=True)

VIGENCIA                   2010                                  \
ESTADO    PERSONA INDETERMINADA PLACA OMISA PÉRDIDA DE POSESIÓN
FUENTE
DETECCION                   102        5400                   1
PARTIDAS                   1163       89030                   1
All                        1265       94430                   2

VIGENCIA                   2011                                  \
ESTADO    PERSONA INDETERMINADA PLACA OMISA PÉRDIDA DE POSESIÓN
FUENTE
DETECCION                   144        5055                   1
PARTIDAS                   2305       98995                   1
All                        2449      104050                   2

VIGENCIA                   2012                                  \
ESTADO    PERSONA INDETERMINADA PLACA OMISA PÉRDIDA DE POSESIÓN
FUENTE
DETECCION                   156        2406                   1
PARTIDAS                   4580      114447                   1
All                        4736      116853                   2

VIGENCIA                   2013  ...        2022                      \
ESTADO    PERSONA INDETERMINADA  ... PLACA OMISA PÉRDIDA DE POSESIÓN
FUENTE                           ...
DETECCION                   168  ...        3344                   2
PARTIDAS                   5329  ...      291080                   3
All                        5497  ...      294424                   5

VIGENCIA                   2023                                  \
ESTADO    PERSONA INDETERMINADA PLACA OMISA PÉRDIDA DE POSESIÓN
FUENTE
DETECCION                 44603        3691                   1
PARTIDAS                  11749      329255                   5
All                       56352      332946                   6

VIGENCIA                   2024                              2025              \
ESTADO    PERSONA INDETERMINADA PLACA OMISA PERSONA INDETERMINADA PLACA OMISA
FUENTE
DETECCION                 58480       25716                 61178      380197
PARTIDAS                   2340      359163                  2954      109520
All                       60820      384879                 64132      489717

VIGENCIA       All
ESTADO
FUENTE
DETECCION   754591
PARTIDAS   3196976
All        3951567

[3 rows x 43 columns]

In [17]:
447858+111790

559648

In [14]:
cartera["MUNICIPIO"].value_counts()

MUNICIPIO
MEDELLIN                             1451634
SIN MUNICIPIO                         446090
BOGOTA                                154608
BELLO                                 148696
ENVIGADO                              106141
                                      ...
MONTELIBANO - LAS MARGARITAS               1
SACAMA                                     1
SAN SEBASTIAN                              1
SAN ANDRES DE TUMACO - PORVENIR            1
MAGANGUE - SAN JOSE DE LAS MARTAS          1
Name: count, Length: 1032, dtype: int64

In [15]:
cartera["CLAVE"] = cartera["PLACA"]+"-"+cartera["VIGENCIA"].astype(str)

In [16]:
cartera[cartera["PLACA"]=="KVT607"]

Empty DataFrame
Columns: [PLACA, ESTADO, MUNICIPIO, DEPARTAMENTO, INTERLOCUTOR_COMERCIAL, ID_USUARIO, TIPO_DOCUMENTO, VIGENCIA, SUBREGION, CLASE, FECHA_MATRICULA, IMPUESTO, SANCIONES, INTERESES, IMPUESTO_CALCULADO, SANCION_CALCULADA, INTERESES_CALCULADOS, PLACA-VIGENCIA, ID_NORMALIZADO_v1, ID_NORMALIZADO, TIPO_PERSONA, NOMBRE_COMPLETO, CLASE_TIPIFICADA, FUENTE, CLAVE]
Index: []

[0 rows x 25 columns]

In [17]:
cartera.shape

(3951567, 25)

In [18]:
cartera.VIGENCIA.value_counts()

VIGENCIA
2025    553849
2024    445699
2023    389304
2022    342984
2021    303654
2020    281402
2019    244337
2018    227016
2017    205121
2016    185433
2015    165262
2014    149227
2013    134490
2012    121591
2011    106501
2010     95697
Name: count, dtype: int64

In [19]:
cartera = cartera[cartera["VIGENCIA"]!=2026]

In [20]:
cartera.VIGENCIA.value_counts()

VIGENCIA
2025    553849
2024    445699
2023    389304
2022    342984
2021    303654
2020    281402
2019    244337
2018    227016
2017    205121
2016    185433
2015    165262
2014    149227
2013    134490
2012    121591
2011    106501
2010     95697
Name: count, dtype: int64

In [21]:
cartera.shape

(3951567, 25)

In [ ]:
pagos = pd.read_csv(r"C:\Users\Katherine Builes L\Downloads\Consolidado pagos 2026.csv",sep=";")
pagos["CLAVE"] = pagos["Placa"]+"-"+pagos["Vigencia"].astype(str)

C:\Users\Katherine Builes L\AppData\Local\Temp\ipykernel_40284\1592885521.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  pagos = pd.read_csv(r"C:\Users\Katherine Builes L\Downloads\Consolidado pagos 2026.csv",sep=";")

In [23]:
pagos.columns

Index(['St_', 'Tipo_de_Pago', 'Cod__Banco', 'Inst__Financiera',
       'Cta__Compens_', 'Cta__Bancaria', 'Lotes_de_pagos', 'Doc_Cobro',
       'Fecha_de_pago', 'Con_Clarif_', 'Vigencia', 'Referencia', 'Placa',
       'Avaluo', 'Valor_del_Lote', 'Valor_Pagado', 'DPP', '_DPP', 'Impuesto',
       'Sanciones', 'Intereses', 'Serv_Inform', 'Benef_Sanciones',
       'Benef_Intereses', 'Municipio', 'Direccion', 'Region', 'Int_Comerc',
       'Creado_Por', 'Fch_Creacion', 'Hr_Creacion', 'Modif_Por', 'Fch_Modif',
       'Hr_Modif', 'Doc_Compens', 'Doc_Clarif'],
      dtype='object')

In [24]:
pagos["CLAVE"] = pagos["Placa"]+"-"+pagos["Vigencia"].astype(str)

In [25]:
cartera = cartera[~cartera["CLAVE"].isin(pagos["CLAVE"])]

In [26]:
cartera[cartera["PLACA"]=="ZZP22G"]

Empty DataFrame
Columns: [PLACA, ESTADO, MUNICIPIO, DEPARTAMENTO, INTERLOCUTOR_COMERCIAL, ID_USUARIO, TIPO_DOCUMENTO, VIGENCIA, SUBREGION, CLASE, FECHA_MATRICULA, IMPUESTO, SANCIONES, INTERESES, IMPUESTO_CALCULADO, SANCION_CALCULADA, INTERESES_CALCULADOS, PLACA-VIGENCIA, ID_NORMALIZADO_v1, ID_NORMALIZADO, TIPO_PERSONA, NOMBRE_COMPLETO, CLASE_TIPIFICADA, FUENTE, CLAVE]
Index: []

[0 rows x 25 columns]

In [27]:
cartera.columns

Index(['PLACA', 'ESTADO', 'MUNICIPIO', 'DEPARTAMENTO',
       'INTERLOCUTOR_COMERCIAL', 'ID_USUARIO', 'TIPO_DOCUMENTO', 'VIGENCIA',
       'SUBREGION', 'CLASE', 'FECHA_MATRICULA', 'IMPUESTO', 'SANCIONES',
       'INTERESES', 'IMPUESTO_CALCULADO', 'SANCION_CALCULADA',
       'INTERESES_CALCULADOS', 'PLACA-VIGENCIA', 'ID_NORMALIZADO_v1',
       'ID_NORMALIZADO', 'TIPO_PERSONA', 'NOMBRE_COMPLETO', 'CLASE_TIPIFICADA',
       'FUENTE', 'CLAVE'],
      dtype='object')

In [ ]:
cartera[]

In [14]:
cartera.shape

(5644939, 24)

In [15]:
cartera.shape

(5644939, 24)

In [16]:
cartera.ESTADO.value_counts()

ESTADO
PLACA OMISA              5133864
PERSONA INDETERMINADA     511046
PÉRDIDA DE POSESIÓN           29
Name: count, dtype: int64

In [17]:
cartera = cartera[cartera["ESTADO"]!="PÉRDIDA DE POSESIÓN"]

In [22]:
cartera.head()

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SUBREGION,CLASE,FECHA_MATRICULA,IMPUESTO,SANCIONES,INTERESES,IMPUESTO_CALCULADO,SANCION_CALCULADA,INTERESES_CALCULADOS,PLACA-VIGENCIA,ID_NORMALIZADO_v1,ID_NORMALIZADO,TIPO_PERSONA,NOMBRE_COMPLETO,CLASE_TIPIFICADA,CLAVE,FUENTE
0,ZXZ97,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,98559636,CC,2009,VALLE DEL ABURRA,MOTOCICLETAS,1992-01-01,NaN,NaN,NaN,NaN,NaN,NaN,ZXZ97-2009,98559636,98559636,PERSONA NATURAL,DUVIAN DARIO BURITICA RAMIREZ,MOTOCICLETAS,ZXZ97-2009,DETECCION
1,ZXZ80,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,98526642,1,2009,VALLE DEL ABURRA,MOTOCICLETAS,1994-01-01,NaN,NaN,NaN,NaN,NaN,NaN,ZXZ80-2009,98526642,98526642,PERSONA NATURAL,OSCAR ALONSO AGUDELO MEJIA,MOTOCICLETAS,ZXZ80-2009,DETECCION
2,ZXZ70,PLACA OMISA,YOLOMBO,ANTIOQUIA,None,71172083,1,2009,NORDESTE,MOTOCICLETAS,1994-01-01,NaN,NaN,NaN,NaN,NaN,NaN,ZXZ70-2009,71172083,71172083,PERSONA NATURAL,NELSON ALBEIRO ORREGO PUERTA,MOTOCICLETAS,ZXZ70-2009,DETECCION
3,ZXZ50,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,8000682800,N,2009,VALLE DEL ABURRA,MOTOCICLETAS,1994-01-01,NaN,NaN,NaN,NaN,NaN,NaN,ZXZ50-2009,8000682800,8000682800,PERSONA JURIDICA,CODEMARCAS LTDA.,MOTOCICLETAS,ZXZ50-2009,DETECCION
4,ZXZ40,PLACA OMISA,LA CEJA,ANTIOQUIA,None,71629485,C,2009,ORIENTE,MOTOCICLETAS,1994-07-08,NaN,NaN,NaN,NaN,NaN,NaN,ZXZ40-2009,71629485,71629485,PERSONA NATURAL,OSCAR ALVARO ECHAVARRIA ORDOÑEZ,MOTOCICLETAS,ZXZ40-2009,DETECCION

In [23]:
cartera.to_parquet("cartera.parquet")

In [35]:
cartera = cartera[[
    "PLACA",
    "ESTADO",
    "MUNICIPIO",
    "DEPARTAMENTO",
    "INTERLOCUTOR_COMERCIAL",
    "ID_USUARIO",
    "TIPO_DOCUMENTO",
    "VIGENCIA",
    "SANCION_CALCULADA",
    "IMPUESTO_CALCULADO",
    "INTERESES_CALCULADOS"
]]

In [36]:
cartera.head()

,PLACA,ESTADO,MUNICIPIO,DEPARTAMENTO,INTERLOCUTOR_COMERCIAL,ID_USUARIO,TIPO_DOCUMENTO,VIGENCIA,SANCION_CALCULADA,IMPUESTO_CALCULADO,INTERESES_CALCULADOS
0,ZXZ97,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,98559636,CC,2010,262000.0,52000.0,218000.0
1,ZXZ80,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,98526642,1,2010,262000.0,11000.0,46000.0
2,ZXZ70,PLACA OMISA,YOLOMBO,ANTIOQUIA,None,71172083,1,2010,262000.0,22000.0,93000.0
3,ZXZ50,PLACA OMISA,MEDELLIN,ANTIOQUIA,None,8000682800,N,2010,262000.0,11000.0,46000.0
4,ZXZ40,PLACA OMISA,LA CEJA,ANTIOQUIA,None,71629485,C,2010,262000.0,11000.0,46000.0

In [38]:
cartera.VIGENCIA.value_counts()

VIGENCIA
2025    550722
2024    444439
2023    388506
2022    342403
2021    303252
2020    281068
2019    244122
2018    226837
2017    204980
2016    185301
2015    165154
2014    149133
2013    134406
2012    121521
2011    106446
2010     95651
Name: count, dtype: int64

In [39]:
cartera.to_parquet("cartera_limpia.parquet")

# CARTERA

In [11]:
pa = pd.read_parquet(r"C:\Users\Katherine Builes L\OneDrive - Valor+ SAS\utilidades\reportes\output\parque_automotor_vigencia_2025.parquet")

In [12]:
pa[pa["PLACA"]=="KVT607"]

,PLACA,ESTADO,ID_USUARIO,TIPO_DOCUMENTO,FUENTE_PROPIETARIO,ESTADO_NOMBRES_APELLIDOS,Personalizado
1333835,KVT607,NOVEDAD,nan,nan,nan,nan,NOVEDAD

In [2]:
import pandas as pd

In [3]:
cartera = pd.read_parquet(r"C:\Users\Katherine Builes L\OneDrive - Valor+ SAS\utilidades\omisos\data omisos\30_04_2026_cartera_fuente.parquet")

In [4]:
cartera.columns

Index(['PLACA', 'ESTADO', 'MUNICIPIO', 'DEPARTAMENTO',
       'INTERLOCUTOR_COMERCIAL', 'ID_USUARIO', 'TIPO_DOCUMENTO', 'VIGENCIA',
       'SUBREGION', 'CLASE', 'FECHA_MATRICULA', 'IMPUESTO', 'SANCIONES',
       'INTERESES', 'IMPUESTO_CALCULADO', 'SANCION_CALCULADA',
       'INTERESES_CALCULADOS', 'PLACA-VIGENCIA', 'ID_NORMALIZADO_v1',
       'ID_NORMALIZADO', 'TIPO_PERSONA', 'NOMBRE_COMPLETO', 'CLASE_TIPIFICADA',
       'FUENTE', 'CLAVE', 'RANGO AVALUO', 'AVALUO'],
      dtype='object')